### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Tacklebox** [CinderBlocc/GoalSpeedAnywhere#1]
I was unable to build the plugin. I am new to windows/c++ development. Could you tell me the steps to build? I cloned bakkesmodorg/BakkesModSDK, I set a windows environment variable called BAKKESMODSDK to the path I cloned it to but I get a no file found error for the import.

**Comment by Tacklebox** [comment]
Also, congratulations on the new job 😁

**Comment by CinderBlocc** [comment]
Thanks! It'll be best if you join the [BakkesMod discord server](https://discord.gg/eXfSfXN) since this sounds like a more generic plugin development issue than anything particular to this repo. Message one of the moderators (or let me know what your discord name#numbers are so I can pass it along) about getting the role to see the programming channel.
