### ISSUE TITLE
No longer shows goal speed in free play with goal scoring disabled

### ISSUE THREAD

**Issue by alexbarrett** [CinderBlocc/GoalSpeedAnywhere#2]
I've used this plugin since release, primarily for seeing goal speed in free play even with goal scoring disabled. A recent Rocket League update (some time in the last few weeks) seems to have broken this and goal speed isn't shown.

**Steps to reproduce**
* Install this plugin
* Go into free play
* Uncheck "Enable goal scoring" under the Bakkesmod Freeplay tab
* Score a goal

**Expected result**
Goal speed is shown by this plugin.

**Actual result**
Goal speed is not shown by this plugin.

**Comment by CinderBlocc** [comment]
Martinn just submitted a pull request that should fix the issue (#3). I don't know when or if the plugin will be updated on the site, so you might be better off pulling from master and building on your own.

**Comment by CinderBlocc** [comment]
Looks like the BM team just uploaded a new version to the website with the fix. Hopefully it starts working for you again automatically.

**Comment by alexbarrett** [comment]
It doesn't work for me still unfortunately.

**Comment by CinderBlocc** [comment]
Ah, that sucks. I'm unable to maintain my old plugins anymore now that I'm a dev at Psyonix, so there's not much I can do about this myself. I'll reopen the issue and leave it open in the hopes that someone can find and submit a fix for it. Sorry about that.

**Comment by alexbarrett** [comment]
Ah shame, I understand though. I hope you're having a great time as part of Psyonix.

I had a look with the function scanner and I can't see any useful events besides the already hooked `TAGame.Ball_TA.OnHitGoal`. Disabling free play goals is a Bakkesmod feature though so I assume the base game must still be triggering that and something in BM has changed to intercept it. Is there anything to that line of logic or could it something in the base game that's changed?

**Comment by CinderBlocc** [comment]
BM has been having issues with the freeplay goals feature recently as well, and they're unsure of the cause. This seems to be related, so it might be something that changed in the game recently. I'm surprised the BallLocation.Y > 5000 thing didn't work though. Hopefully someone from the BM programming server can take a look at this and figure out the root cause of the issue.

**Comment by alexbarrett** [comment]
> I'm surprised the BallLocation.Y > 5000 thing didn't work though.

Is it because the PR didn't update the version number?

**Comment by CinderBlocc** [comment]
Nah, version numbers in plugins are just for display, or so that the plugin dev can determine which version someone is using by looking at their logs.

**Comment by alexbarrett** [comment]
I thought it might be used by the plugin auto-updater as well and it didn't work for me because I didn't update manually.

**Comment by Timmeey86** [comment]
It appears Psyonix changed the events which get sent when a goal is scored, which unfortunately results in no more events being sent when goal scoring is turned off.
I'm working on a solution and the current one looks promising, but it requires a lot of testing due to custom maps, hoops, dropshot etc. So let me know if someone else is already working on this, in here or on Bakkesmod Plugin discord ;)
